#!/bin/bash
tables=$(awk '/CREATE TABLE/ {print $3}' "$BACKUP_SCHEMA_FILE" | tr -d ';')

echo "$tables" | while read -r table; do
  if [[ ! -z "$table" ]]; then
    echo "Backing up $table"
    filename=$(echo $table | sed 's/\./_/g').sql.gz
    pg_dump -h "$HOST" -U "$USER" -d "$DB_NAME" -t "$table" | gzip > "$BACKUP_DIR/$filename"
  fi
done
