#!/bin/bash
aws s3 cp ./src/schema/backup_tables/ s3://snapshots/historical/ --recursive --endpoint-url https://racehorse-database-backup.fra1.digitaloceanspaces.com --profile digitalocean
aws s3 cp ./src/schema/backup_files/racehorse-database-schema.sql s3://snapshots/schemas/ --endpoint-url https://racehorse-database-backup.fra1.digitaloceanspaces.com --profile digitalocean
