#!/bin/bash
pg_dump -h racing-api-do-user-11198504-0.c.db.ondigitalocean.com -p 25060 -U doadmin racehorse-database | psql -h localhost -U tom.wattley -d racehorse-database

pg_dump -h localhost -p 5432 -U tom.wattley -d racehorse-database | psql -h racing-api-do-user-11198504-0.c.db.ondigitalocean.com -p 25060 -U doadmin racehorse-database

