ALTER TABLE rp_raw.performance_data
    ALTER COLUMN horse_id TYPE character varying(32),
    ALTER COLUMN horse_name TYPE character varying(132),
    ALTER COLUMN horse_age TYPE character varying(16),
    ALTER COLUMN jockey_id TYPE character varying(32),
    ALTER COLUMN jockey_name TYPE character varying(132),
    ALTER COLUMN jockey_claim TYPE character varying(16),
    ALTER COLUMN trainer_id TYPE character varying(32),
    ALTER COLUMN trainer_name TYPE character varying(132),
    ALTER COLUMN owner_id TYPE character varying(32),
    ALTER COLUMN owner_name TYPE character varying(132),
    ALTER COLUMN horse_weight TYPE character varying(16),
    ALTER COLUMN or_value TYPE character varying(16),
    ALTER COLUMN finishing_position TYPE character varying(16),
    ALTER COLUMN draw TYPE character varying(16),
    ALTER COLUMN ts_value TYPE character varying(16),
    ALTER COLUMN rpr_value TYPE character varying(16),
    ALTER COLUMN horse_price TYPE character varying(16),
    ALTER COLUMN extra_weight TYPE numeric,
    ALTER COLUMN headgear TYPE character varying(16),
    ALTER COLUMN sire_name TYPE character varying(132),
    ALTER COLUMN sire_id TYPE character varying(32),
    ALTER COLUMN dam_name TYPE character varying(132),
    ALTER COLUMN dam_id TYPE character varying(32),
    ALTER COLUMN dams_sire TYPE character varying(132),
    ALTER COLUMN dams_sire_id TYPE character varying(32),
    ALTER COLUMN race_date TYPE character varying(16),
    ALTER COLUMN race_time TYPE character varying(16),
    ALTER COLUMN race_timestamp TYPE timestamp without time zone,
    ALTER COLUMN conditions TYPE character varying(16),
    ALTER COLUMN distance TYPE character varying(16),
    ALTER COLUMN going TYPE character varying(16),
    ALTER COLUMN winning_time TYPE character varying(16),
    ALTER COLUMN number_of_runners TYPE character varying(16),
    ALTER COLUMN total_prize_money TYPE integer,
    ALTER COLUMN first_place_prize_money TYPE integer,
    ALTER COLUMN currency TYPE character varying(16),
    ALTER COLUMN course_id TYPE character varying(32),
    ALTER COLUMN course_name TYPE character varying(132),
    ALTER COLUMN course TYPE character varying(132),
    ALTER COLUMN race_id TYPE character varying(32),
    ALTER COLUMN country TYPE character varying(16),
    ALTER COLUMN surface TYPE character varying(16),
    ALTER COLUMN unique_id TYPE character varying(132);


ALTER TABLE tf_raw.performance_data
    ALTER COLUMN tf_rating TYPE character varying(16),
    ALTER COLUMN tf_speed_figure TYPE character varying(16),
    ALTER COLUMN draw TYPE character varying(16),
    ALTER COLUMN trainer_name TYPE character varying(132),
    ALTER COLUMN trainer_id TYPE character varying(32),
    ALTER COLUMN jockey_name TYPE character varying(132),
    ALTER COLUMN jockey_id TYPE character varying(32),
    ALTER COLUMN sire_name TYPE character varying(132),
    ALTER COLUMN sire_id TYPE character varying(32),
    ALTER COLUMN dam_name TYPE character varying(132),
    ALTER COLUMN dam_id TYPE character varying(32),
    ALTER COLUMN finishing_position TYPE character varying(16),
    ALTER COLUMN horse_name TYPE character varying(132),
    ALTER COLUMN horse_id TYPE character varying(32),
    ALTER COLUMN horse_name_link TYPE character varying(132),
    ALTER COLUMN horse_age TYPE character varying(16),
    ALTER COLUMN equipment TYPE character varying(16),
    ALTER COLUMN official_rating TYPE character varying(16),
    ALTER COLUMN fractional_price TYPE character varying(16),
    ALTER COLUMN betfair_win_sp TYPE character varying(16),
    ALTER COLUMN betfair_place_sp TYPE character varying(16),
    ALTER COLUMN in_play_prices TYPE character varying(16),
    ALTER COLUMN tf_comment TYPE text,
    ALTER COLUMN course TYPE character varying(132),
    ALTER COLUMN race_date TYPE character varying(16),
    ALTER COLUMN race_time TYPE character varying(16),
    ALTER COLUMN race_timestamp TYPE timestamp without time zone,
    ALTER COLUMN course_id TYPE character varying(32),
    ALTER COLUMN race TYPE text,
    ALTER COLUMN race_id TYPE character varying(32),
    ALTER COLUMN distance TYPE character varying(16),
    ALTER COLUMN going TYPE character varying(16),
    ALTER COLUMN prize TYPE character varying(16),
    ALTER COLUMN hcap_range TYPE character varying(16),
    ALTER COLUMN age_range TYPE character varying(16),
    ALTER COLUMN race_type TYPE character varying(16),
    ALTER COLUMN main_race_comment TYPE text,
    ALTER COLUMN debug_link TYPE text,
    ALTER COLUMN created_at TYPE timestamp without time zone,
    ALTER COLUMN sire_name_link TYPE character varying(132),
    ALTER COLUMN unique_id TYPE character varying(132);
