#!/usr/bin/env zsh
export LOG_LEVEL="INFO"
echo "Changing directory to $RACING_ETL_FOLDER"
echo "Changing directory to $RACING_ETL_ENV"
cd $RACING_ETL_FOLDER 
echo "Current directory: $(pwd)"
source ~/.zshrc
echo "Sourcing environment from $RACING_ETL_ENV"
source $RACING_ETL_ENV
echo "Python version: $(python --version)" 
echo

case $1 in
    "tf_scrape_links")
        echo "Running tf_scrape_links"
        export ENV="development"
        python $RACING_ETL_FOLDER/src/raw/timeform/scrape_links.py
        ;;
    "tf_scrape_data")
        echo "Running tf_scrape_data"
        export ENV="development"
        python $RACING_ETL_FOLDER/src.raw.timeform.scrape_data.py
        ;;
    "rp_scrape_links")
        echo "Running rp_scrape_links"
        python $RACING_ETL_FOLDER/src/raw/racing-post/scrape_links.py
        ;;
    "rp_scrape_data")
        echo "Running rp_scrape_data"
        python $RACING_ETL_FOLDER/src/raw/racing-post/scrape_data.py
        ;;
    *)
        echo "Invalid command"
        ;;
esac
