class RawSQLGenerator:
    @staticmethod
    def define_upsert_sql(
        table_name: str,
    ):
        return f"""
        INSERT INTO rp_raw.{table_name}(
            race_time,
            race_date,
            course_name,
            race_class,
            horse_name,
            horse_type,
            horse_age,
            headgear,
            conditions,
            horse_price,
            race_title,
            distance,
            distance_full,
            going,
            number_of_runners,
            total_prize_money,
            first_place_prize_money,
            winning_time,
            official_rating,
            horse_weight,
            draw,
            country,
            surface,
            finishing_position,
            total_distance_beaten,
            ts_value,
            rpr_value,
            extra_weight,
            comment,
            race_time_debug,
            currency,
            course,
            jockey_name,
            jockey_claim,
            trainer_name,
            sire_name,
            dam_name,
            dams_sire,
            owner_name,
            horse_id,
            trainer_id,
            jockey_id,
            sire_id,
            dam_id,
            dams_sire_id,
            owner_id,
            race_id,
            course_id,
            meeting_id,
            unique_id,
            debug_link,
            created_at
        )
        SELECT
            race_time,
            race_date,
            course_name,
            race_class,
            horse_name,
            horse_type,
            horse_age,
            headgear,
            conditions,
            horse_price,
            race_title,
            distance,
            distance_full,
            going,
            number_of_runners,
            total_prize_money,
            first_place_prize_money,
            winning_time,
            official_rating,
            horse_weight,
            draw,
            country,
            surface,
            finishing_position,
            total_distance_beaten,
            ts_value,
            rpr_value,
            extra_weight,
            comment,
            race_time_debug,
            currency,
            course,
            jockey_name,
            jockey_claim,
            trainer_name,
            sire_name,
            dam_name,
            dams_sire,
            owner_name,
            horse_id,
            trainer_id,
            jockey_id,
            sire_id,
            dam_id,
            dams_sire_id,
            owner_id,
            race_id,
            course_id,
            meeting_id,
            unique_id,
            debug_link,
            created_at
        FROM
            rp_raw_{table_name}_tmp_load
        ON CONFLICT(unique_id)
            DO UPDATE SET
                race_time = EXCLUDED.race_time,
                race_date = EXCLUDED.race_date,
                course_name = EXCLUDED.course_name,
                race_class = EXCLUDED.race_class,
                horse_name = EXCLUDED.horse_name,
                horse_type = EXCLUDED.horse_type,
                horse_age = EXCLUDED.horse_age,
                headgear = EXCLUDED.headgear,
                conditions = EXCLUDED.conditions,
                horse_price = EXCLUDED.horse_price,
                race_title = EXCLUDED.race_title,
                distance = EXCLUDED.distance,
                distance_full = EXCLUDED.distance_full,
                going = EXCLUDED.going,
                number_of_runners = EXCLUDED.number_of_runners,
                total_prize_money = EXCLUDED.total_prize_money,
                first_place_prize_money = EXCLUDED.first_place_prize_money,
                winning_time = EXCLUDED.winning_time,
                official_rating = EXCLUDED.official_rating,
                horse_weight = EXCLUDED.horse_weight,
                draw = EXCLUDED.draw,
                country = EXCLUDED.country,
                surface = EXCLUDED.surface,
                finishing_position = EXCLUDED.finishing_position,
                total_distance_beaten = EXCLUDED.total_distance_beaten,
                ts_value = EXCLUDED.ts_value,
                rpr_value = EXCLUDED.rpr_value,
                extra_weight = EXCLUDED.extra_weight,
                comment = EXCLUDED.comment,
                race_time_debug = EXCLUDED.race_time_debug,
                currency = EXCLUDED.currency,
                course = EXCLUDED.course,
                jockey_name = EXCLUDED.jockey_name,
                jockey_claim = EXCLUDED.jockey_claim,
                trainer_name = EXCLUDED.trainer_name,
                sire_name = EXCLUDED.sire_name,
                dam_name = EXCLUDED.dam_name,
                dams_sire = EXCLUDED.dams_sire,
                owner_name = EXCLUDED.owner_name,
                horse_id = EXCLUDED.horse_id,
                trainer_id = EXCLUDED.trainer_id,
                jockey_id = EXCLUDED.jockey_id,
                sire_id = EXCLUDED.sire_id,
                dam_id = EXCLUDED.dam_id,
                dams_sire_id = EXCLUDED.dams_sire_id,
                owner_id = EXCLUDED.owner_id,
                race_id = EXCLUDED.race_id,
                course_id = EXCLUDED.course_id,
                meeting_id = EXCLUDED.meeting_id,
                unique_id = EXCLUDED.unique_id,
                debug_link = EXCLUDED.debug_link,
                created_at = EXCLUDED.created_at;
            """

    @staticmethod
    def get_results_data_upsert_sql():
        return RawSQLGenerator.define_upsert_sql("results_data")

    @staticmethod
    def get_results_data_world_upsert_sql():
        return RawSQLGenerator.define_upsert_sql("results_data_world")
