class LoadSQLGenerator:
    @staticmethod
    def define_upsert_sql():
        return """
            TRUNCATE public.unioned_results_data;

            INSERT INTO public.unioned_results_data (
                horse_name,
                age,
                horse_sex,
                draw,
                headgear,
                weight_carried,
                weight_carried_lbs,
                extra_weight,
                jockey_claim,
                finishing_position,
                total_distance_beaten,
                industry_sp,
                betfair_win_sp,
                betfair_place_sp,
                official_rating,
                ts,
                rpr,
                tfr,
                tfig,
                in_play_high,
                in_play_low,
                in_race_comment,
                tf_comment,
                tfr_view,
                race_id,
                horse_id,
                jockey_id,
                trainer_id,
                owner_id,
                sire_id,
                dam_id,
                unique_id,
                race_time,
                race_date,
                race_title,
                race_type,
                race_class,
                distance,
                distance_yards,
                distance_meters,
                distance_kilometers,
                conditions,
                going,
                number_of_runners,
                hcap_range,
                age_range,
                surface,
                total_prize_money,
                first_place_prize_money,
                winning_time,
                time_seconds,
                relative_time,
                relative_to_standard,
                country,
                main_race_comment,
                meeting_id,
                course_id,
                course,
                dam,
                sire,
                trainer,
                jockey,
                created_at,
                data_type
            )
            SELECT
                horse_name,
                age,
                horse_sex,
                draw,
                headgear,
                weight_carried,
                weight_carried_lbs,
                extra_weight,
                jockey_claim,
                NULL AS finishing_position,
                NULL AS total_distance_beaten,
                NULL AS industry_sp,
                NULL AS betfair_win_sp,
                NULL AS betfair_place_sp,
                official_rating,
                NULL AS ts,
                NULL AS rpr,
                NULL AS tfr,
                NULL AS tfig,
                NULL AS in_play_high,
                NULL AS in_play_low,
                NULL AS in_race_comment,
                NULL AS tf_comment,
                NULL AS tfr_view,
                race_id,
                horse_id,
                jockey_id,
                trainer_id,
                owner_id,
                sire_id,
                dam_id,
                unique_id,
                race_time,
                race_date,
                race_title,
                race_type,
                race_class,
                distance,
                distance_yards,
                distance_meters,
                distance_kilometers,
                conditions,
                going,
                number_of_runners,
                hcap_range,
                age_range,
                surface,
                total_prize_money,
                first_place_prize_money,
                NULL AS winning_time,
                NULL AS time_seconds,
                NULL AS relative_time,
                NULL AS relative_to_standard,
                country,
                NULL AS main_race_comment,
                meeting_id,
                course_id,
                course,
                dam,
                sire,
                trainer,
                jockey,
                created_at,
                'today' AS data_type
            FROM
                public.todays_data
            UNION
            SELECT
                horse_name,
                age,
                horse_sex,
                draw,
                headgear,
                weight_carried,
                weight_carried_lbs,
                extra_weight,
                jockey_claim,
                finishing_position,
                total_distance_beaten,
                industry_sp,
                betfair_win_sp,
                betfair_place_sp,
                official_rating,
                ts,
                rpr,
                tfr,
                tfig,
                in_play_high,
                in_play_low,
                in_race_comment,
                tf_comment,
                tfr_view,
                race_id,
                horse_id,
                jockey_id,
                trainer_id,
                owner_id,
                sire_id,
                dam_id,
                unique_id,
                race_time,
                race_date,
                race_title,
                race_type,
                race_class,
                distance,
                distance_yards,
                distance_meters,
                distance_kilometers,
                conditions,
                going,
                number_of_runners,
                hcap_range,
                age_range,
                surface,
                total_prize_money,
                first_place_prize_money,
                winning_time,
                time_seconds,
                relative_time,
                relative_to_standard,
                country,
                main_race_comment,
                meeting_id,
                course_id,
                course,
                dam,
                sire,
                trainer,
                jockey,
                created_at,
                'historical' AS data_type
            FROM
                public.results_data;



            """

    @staticmethod
    def get_unioned_results_data_upsert_sql():
        return LoadSQLGenerator.define_upsert_sql()
