name: Pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          
      - name: Unit tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest tests/unit

      - name: Run docker
        run: |
          docker-compose up -d
        shell: bash

      - name: Unit tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest tests/unit

      - name: Run docker
        run: |
          docker-compose up -d
        shell: bash

      - name: Wait for PostgreSQL to start
        run: |
          echo "Waiting for PostgreSQL to start..."
          while ! pg_isready -h localhost -p 5433 -U test_user; do
            sleep 1
          done
          echo "PostgreSQL is ready"

      - name: Integration tests
        env:
          PYTHONPATH: ${{ github.workspace }} 
        run: |
          pytest tests/integration
