from dataclasses import dataclass
from datetime import datetime


@dataclass
class RacingPostDataModel:
    race_timestamp: datetime
    race_date: str
    course_name: str
    race_class: str
    horse_name: str
    horse_type: str
    horse_age: str
    headgear: str
    conditions: str
    horse_price: str
    race_title: str
    distance: str
    distance_full: str
    going: str
    number_of_runners: str
    total_prize_money: int
    first_place_prize_money: int
    winning_time: str
    official_rating: str
    horse_weight: str
    draw: str
    country: str
    surface: str
    finishing_position: str
    total_distance_beaten: str
    ts_value: str
    rpr_value: str
    extra_weight: float
    comment: str
    race_time: str
    currency: str
    course: str
    jockey_name: str
    jockey_claim: str
    trainer_name: str
    sire_name: str
    dam_name: str
    dams_sire: str
    owner_name: str
    horse_id: str
    trainer_id: str
    jockey_id: str
    sire_id: str
    dam_id: str
    dams_sire_id: str
    owner_id: str
    race_id: str
    course_id: str
    meeting_id: str
    unique_id: str
    debug_link: str
    created_at: datetime


table_string_field_lengths = {
    "race_date": 32,
    "course_name": 132,
    "race_class": 132,
    "horse_name": 132,
    "horse_type": 16,
    "horse_age": 16,
    "headgear": 16,
    "conditions": 32,
    "horse_price": 16,
    "distance": 32,
    "distance_full": 32,
    "going": 32,
    "number_of_runners": 32,
    "winning_time": 32,
    "official_rating": 16,
    "horse_weight": 16,
    "draw": 16,
    "country": 16,
    "surface": 16,
    "finishing_position": 16,
    "total_distance_beaten": 32,
    "ts_value": 16,
    "rpr_value": 16,
    "race_time": 32,
    "currency": 16,
    "course": 132,
    "jockey_name": 132,
    "jockey_claim": 16,
    "trainer_name": 132,
    "sire_name": 132,
    "dam_name": 132,
    "dams_sire": 132,
    "owner_name": 132,
    "horse_id": 32,
    "trainer_id": 32,
    "jockey_id": 32,
    "sire_id": 32,
    "dam_id": 32,
    "dams_sire_id": 32,
    "owner_id": 32,
    "race_id": 32,
    "course_id": 32,
    "meeting_id": 132,
    "unique_id": 132,
}
